name: Test
on: 
  workflow_run:
    workflows:
      - "Toto"
    types:
      - "completed"
jobs: 
  Tests: 
    runs-on: ubuntu-latest
    steps:
      - uses: anfi-semifir/actions-hello@1.0.0
        
